"""Initial migration

Revision ID: 29bd9487f961
Revises: 
Create Date: 2024-10-17 23:39:07.018146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29bd9487f961'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pluggy_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_key', sa.String(), nullable=True),
    sa.Column('api_key_expiration', sa.DateTime(), nullable=True),
    sa.Column('connect_token', sa.String(), nullable=True),
    sa.Column('connect_token_expiration', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pluggy_config_id'), 'pluggy_config', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pluggy_config_id'), table_name='pluggy_config')
    op.drop_table('pluggy_config')
    # ### end Alembic commands ###
